steps:
  # =====================================================
  # STAGE 1: QUALITY GATE (Run the Tests)
  # =====================================================
  - name: 'python:3.11'
    id: 'run-eval-tests'
    entrypoint: 'bash'
    env:
      - 'GCP_PROJECT_ID=$PROJECT_ID'
    args:
      - '-c'
      - |
        echo "🔹 [Stage 1] Installing Dependencies..."
        pip install -r requirements.txt
        
        echo "🔹 [Stage 1] Running Evaluation Loop..."
        python3 tests/evaluate.py

  # =====================================================
  # STAGE 2: CLOUD RUN DEPLOY (Web App)
  # =====================================================
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'deploy-cloud-run'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'brady-logistics-agent'
      - '--source=.'
      - '--region=us-central1'
      - '--allow-unauthenticated'
      - '--set-env-vars=GCP_PROJECT_ID=$PROJECT_ID'
      # ---------------------------------------------------
      # CRITICAL FIX: Clears conflict between Buildpacks & Dockerfile
      # ---------------------------------------------------
      - '--clear-base-image'
    waitFor: ['run-eval-tests']

  # =====================================================
  # STAGE 3: AGENT ENGINE DEPLOY (SaaS)
  # =====================================================
  - name: 'python:3.11' 
    id: 'deploy-agent-engine'
    entrypoint: 'bash'
    env:
      - 'GCP_PROJECT_ID=$PROJECT_ID'
      - 'REGION=us-central1' 
      - 'GOOGLE_CLOUD_AGENT_ENGINE_ENABLE_TELEMETRY=true'
      - 'OTEL_INSTRUMENTATION_GENAI_CAPTURE_MESSAGE_CONTENT=true'
    args:
      - '-c'
      - |
        echo "🔹 [Stage 3] Installing ADK..."
        pip install google-adk
        
        echo "🔹 [Stage 3] Deploying to Vertex AI Agent Engine..."
        adk deploy agent_engine brady_agent \
          --project $PROJECT_ID \
          --region us-central1 \
          --display_name "Brady Logistics Agent"

    waitFor: ['run-eval-tests']

timeout: '900s'