steps:
  # =====================================================
  # STAGE 1: INSTALL & TEST (All-in-one to avoid path errors)
  # =====================================================
  - name: 'python:3.11'
    id: 'run-eval-tests'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "🔹 Installing dependencies..."
        pip install --upgrade pip
        pip install -r requirements.txt
        
        echo "🔹 Running Pytest..."
        # Using 'python3 -m' is the secret to making pytest work in Cloud Build
        python3 -m pytest tests/

  # =====================================================
  # STAGE 2: AGENT ENGINE DEPLOY (Pure & Simple)
  # =====================================================
  - name: 'python:3.11'
    id: 'deploy-agent-engine'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "🔹 Installing ADK..."
        pip install google-adk
        
        echo "🔹 Deploying Agent Engine to $PROJECT_ID..."
        # This uses your repo's .env for telemetry 
        # and $PROJECT_ID for the cloud destination.
        adk deploy agent_engine brady_agent \
          --project $PROJECT_ID \
          --region us-central1 \
          --display_name "Brady Logistics Agent" \
          --env_file .env \
          --requirements_file requirements.txt \
          --trace_to_cloud

    waitFor: ['run-eval-tests']

options:
  logging: CLOUD_LOGGING_ONLY