steps:
  # =====================================================
  # STAGE 1: QUALITY GATE (Run the Tests)
  # =====================================================
  - name: 'python:3.11'
    id: 'run-eval-tests'
    entrypoint: 'bash'
    env:
      - 'GCP_PROJECT_ID=$PROJECT_ID'
    args:
      - '-c'
      - |
        echo "🔹 [Stage 1] Installing Dependencies..."
        pip install -r requirements.txt
        
        echo "🔹 [Stage 1] Running Evaluation Loop..."
        python3 tests/evaluate.py

  # =====================================================
  # STAGE 2: CLOUD RUN DEPLOY (Web App)
  # =====================================================
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'deploy-cloud-run'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'brady-logistics-agent'
      - '--source=.'
      - '--region=us-central1'
      - '--allow-unauthenticated'
      - '--set-env-vars=GCP_PROJECT_ID=$PROJECT_ID'
      - '--clear-base-image'
    waitFor: ['run-eval-tests']

  # =====================================================
  # STAGE 3: AGENT ENGINE DEPLOY (Working ADK + Telemetry)
  # =====================================================
  - name: 'python:3.11' 
    id: 'deploy-agent-engine'
    entrypoint: 'bash'
    # We use the built-in PROJECT_ID directly, no custom env vars.
    args:
      - '-c'
      - |
        echo "🔹 [Stage 3] Installing ADK..."
        pip install google-adk

        # --- STEP 1: Add Telemetry Deps ---
        echo "🔹 [Stage 3] Adding Telemetry libraries..."
        echo "opentelemetry-sdk" >> requirements.txt
        echo "opentelemetry-exporter-google-cloud" >> requirements.txt

        # --- STEP 2: Inject Config (The "Patch") ---
        echo "🔹 [Stage 3] Configuring Agent for Telemetry..."
        # We use sed to insert lines at the top of the file (Line 1).
        # We use the built-in $PROJECT_ID variable.
        sed -i "1s|^|import os\nos.environ['GOOGLE_CLOUD_AGENT_ENGINE_ENABLE_TELEMETRY'] = 'true'\nos.environ['OTEL_INSTRUMENTATION_GENAI_CAPTURE_MESSAGE_CONTENT'] = 'true'\n|" brady_agent/agent.py

        # --- STEP 3: Deploy (Your Working Command) ---
        echo "🔹 [Stage 3] Deploying to Vertex AI..."
        
        # We use the standard $PROJECT_ID provided by Cloud Build
        adk deploy agent_engine brady_agent \
          --project $PROJECT_ID \
          --region us-central1 \
          --display_name "Brady Logistics Agent (v$BUILD_ID)"

    waitFor: ['run-eval-tests']

timeout: '900s'