steps:
  # =====================================================
  # STAGE 1: QUALITY GATE (Run the Tests)
  # =====================================================
  - name: 'python:3.11'
    id: 'run-eval-tests'
    entrypoint: 'bash'
    env:
      - 'GCP_PROJECT_ID=$PROJECT_ID'
    args:
      - '-c'
      - |
        echo "🔹 [Stage 1] Installing Dependencies..."
        pip install -r requirements.txt
        
        echo "🔹 [Stage 1] Running Evaluation Loop..."
        python3 tests/evaluate.py

  # =====================================================
  # STAGE 2: CLOUD RUN DEPLOY (Web App)
  # =====================================================
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'deploy-cloud-run'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'brady-logistics-agent'
      - '--source=.'
      - '--region=us-central1'
      - '--allow-unauthenticated'
      - '--set-env-vars=GCP_PROJECT_ID=$PROJECT_ID'
      - '--clear-base-image'
    waitFor: ['run-eval-tests']

  # =====================================================
  # STAGE 3: AGENT ENGINE DEPLOY (Working Bash + Telemetry Injection)
  # =====================================================
  - name: 'python:3.11' 
    id: 'deploy-agent-engine'
    entrypoint: 'bash'
    env:
      - 'GCP_PROJECT_ID=$PROJECT_ID'
    args:
      - '-c'
      - |
        echo "🔹 [Stage 3] Installing ADK..."
        pip install google-adk

        # --- FIX 1: Add Telemetry Libraries ---
        echo "🔹 [Stage 3] Adding Telemetry libraries to requirements.txt..."
        # We ensure the container has the code needed to send traces
        echo "opentelemetry-sdk" >> requirements.txt
        echo "opentelemetry-exporter-google-cloud" >> requirements.txt

        # --- FIX 2: Inject Configuration into Code ---
        echo "🔹 [Stage 3] Injecting Telemetry Config into agent.py..."
        
        # We write a header that forces the variables to TRUE inside the python process
        cat <<EOF > telemetry_header.py
        import os
        # Force Telemetry ON (Injected by Cloud Build)
        os.environ['GOOGLE_CLOUD_AGENT_ENGINE_ENABLE_TELEMETRY'] = 'true'
        os.environ['OTEL_INSTRUMENTATION_GENAI_CAPTURE_MESSAGE_CONTENT'] = 'true'
        EOF

        # We prepend this header to your existing agent file
        # temp_file = header + original_code
        cat telemetry_header.py brady_agent/agent.py > brady_agent/agent_temp.py
        
        # Overwrite the original with the new "Telemetry Enabled" version
        mv brady_agent/agent_temp.py brady_agent/agent.py

        # --- ORIGINAL DEPLOYMENT COMMAND ---
        echo "🔹 [Stage 3] Deploying to Vertex AI Agent Engine..."
        adk deploy agent_engine brady_agent \
          --project $GCP_PROJECT_ID \
          --region us-central1 \
          --display_name "Brady Logistics Agent (v$BUILD_ID)"

    waitFor: ['run-eval-tests']

timeout: '900s'