steps:
  # =====================================================
  # STAGE 1: QUALITY GATE (Run the Tests)
  # =====================================================
  - name: 'python:3.11'
    id: 'run-eval-tests'
    entrypoint: 'bash'
    env:
      - 'GCP_PROJECT_ID=$PROJECT_ID'
    args:
      - '-c'
      - |
        echo "🔹 [Stage 1] Installing Dependencies..."
        pip install -r requirements.txt
        
        echo "🔹 [Stage 1] Running Evaluation Loop..."
        python3 tests/evaluate.py

  # =====================================================
  # STAGE 2: CLOUD RUN DEPLOY (Web App)
  # =====================================================
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'deploy-cloud-run'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'brady-logistics-agent'
      - '--source=.'
      - '--region=us-central1'
      - '--allow-unauthenticated'
      - '--set-env-vars=GCP_PROJECT_ID=$PROJECT_ID'
      - '--clear-base-image'
    waitFor: ['run-eval-tests']

  # =====================================================
  # STAGE 3: AGENT ENGINE DEPLOY (Hardcoded Region & Fixes)
  # =====================================================
  - name: 'python:3.11' 
    id: 'deploy-agent-engine'
    entrypoint: 'bash'
    env:
      - 'GCP_PROJECT_ID=$PROJECT_ID'
      # Removed 'REGION' env var to fix the substitution error
    args:
      - '-c'
      - |
        echo "🔹 [Stage 3] Installing LATEST Deploy Dependencies..."
        pip install --upgrade "google-cloud-aiplatform[reasoningengine,langchain]" google-adk python-dotenv

        # --- 1. PREPARE THE BUCKET ---
        echo "🔹 [Stage 3] Ensuring bucket exists: gs://adk_agent_engine_staging"
        # Hardcoded region 'us-central1'
        gcloud storage buckets create gs://adk_agent_engine_staging --location=us-central1 --uniform-bucket-level-access || true

        # --- 2. CODE INJECTION (THE CRASH FIX) ---
        echo "🔹 [Stage 3] Patching agent.py to initialize Vertex AI immediately..."
        
        # We inject hardcoded 'us-central1' directly into the patch
        PYTHON_PATCH="import os\nimport vertexai\nvertexai.init(project='$PROJECT_ID', location='us-central1')\nos.environ['GCP_PROJECT_ID'] = '$PROJECT_ID'\nos.environ['GOOGLE_CLOUD_AGENT_ENGINE_ENABLE_TELEMETRY'] = 'true'\nos.environ['OTEL_INSTRUMENTATION_GENAI_CAPTURE_MESSAGE_CONTENT'] = 'true'\n"
        
        sed -i "1s|^|$PYTHON_PATCH|" brady_agent/agent.py
        
        head -n 8 brady_agent/agent.py

        echo "🔹 [Stage 3] Generating Deploy Script..."
        cat <<EOF > run_deploy.py
        import os
        import vertexai
        from vertexai.preview import reasoning_engines
        
        # Import the now-patched agent
        from brady_agent.agent import root_agent 

        project_id = os.environ.get("GCP_PROJECT_ID")
        # Hardcoded region
        location = "us-central1"
        staging_bucket = "gs://adk_agent_engine_staging"

        print(f"🚀 Connecting to Vertex AI in {project_id}...")
        vertexai.init(project=project_id, location=location, staging_bucket=staging_bucket)

        print("🚀 Deploying to Vertex AI...")
        
        remote_agent = reasoning_engines.ReasoningEngine.create(
            root_agent,
            requirements=[
                "google-cloud-aiplatform[reasoningengine,langchain]", 
                "python-dotenv", 
                "google-adk",
                "opentelemetry-sdk",
                "opentelemetry-exporter-google-cloud"
            ],
            display_name="Brady Logistics Agent",
            description="Logistics assistant (Observability Enabled)"
        )
        print(f"✅ Deployment Complete! Resource: {remote_agent.resource_name}")
        EOF

        echo "🔹 [Stage 3] Executing Deployment..."
        python3 run_deploy.py

    waitFor: ['run-eval-tests']

timeout: '900s'