steps:
  # =====================================================
  # STAGE 1: QUALITY GATE (Run the Tests)
  # =====================================================
  - name: 'python:3.11'
    id: 'run-eval-tests'
    entrypoint: 'bash'
    env:
      - 'GCP_PROJECT_ID=$PROJECT_ID'
    args:
      - '-c'
      - |
        echo "🔹 [Stage 1] Installing Dependencies..."
        pip install -r requirements.txt
        
        echo "🔹 [Stage 1] Running Evaluation Loop..."
        python3 tests/evaluate.py

  # =====================================================
  # STAGE 2: CLOUD RUN DEPLOY (Web App)
  # =====================================================
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'deploy-cloud-run'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'brady-logistics-agent'
      - '--source=.'
      - '--region=us-central1'
      - '--allow-unauthenticated'
      - '--set-env-vars=GCP_PROJECT_ID=$PROJECT_ID'
      - '--clear-base-image'
    waitFor: ['run-eval-tests']

# =====================================================
  # STAGE 3: AGENT ENGINE DEPLOY (Corrected Path)
  # =====================================================
  - name: 'python:3.11' 
    id: 'deploy-agent-engine'
    entrypoint: 'bash'
    env:
      - 'GCP_PROJECT_ID=$PROJECT_ID'
      - 'REGION=us-central1' 
    args:
      - '-c'
      - |
        echo "🔹 [Stage 3] Installing Deploy Dependencies..."
        pip install google-cloud-aiplatform google-adk python-dotenv

        echo "🔹 [Stage 3] Generating Deploy Script..."
        cat <<EOF > run_deploy.py
        import os
        from google.cloud import aiplatform
        
        # FIX: Import from the folder 'brady_agent' seen in your screenshot
        from brady_agent.agent import root_agent 

        project_id = os.environ.get("GCP_PROJECT_ID")
        location = os.environ.get("REGION", "us-central1")

        print(f"🚀 Connecting to Vertex AI in {project_id}...")
        aiplatform.init(project=project_id, location=location)

        print("🚀 Deploying 'brady_agent' with Telemetry ENABLED...")
        
        # We deploy the 'root_agent' object we just imported
        remote_agent = aiplatform.reasoning_engines.ReasoningEngine.create(
            root_agent,
            requirements=["google-cloud-aiplatform", "python-dotenv", "google-adk"],
            display_name="Brady Logistics Agent",
            description="Logistics assistant (Observability Enabled)",
            
            # INFRASTRUCTURE SWITCH FOR TELEMETRY
            env_vars={
                "GOOGLE_CLOUD_AGENT_ENGINE_ENABLE_TELEMETRY": "true",
                "OTEL_INSTRUMENTATION_GENAI_CAPTURE_MESSAGE_CONTENT": "true"
            }
        )
        print(f"✅ Deployment Complete! Resource: {remote_agent.resource_name}")
        EOF

        echo "🔹 [Stage 3] Executing Deployment..."
        python3 run_deploy.py

    waitFor: ['run-eval-tests']