steps:
  # =====================================================
  # STAGE 1: QUALITY GATE (Merged for reliability)
  # =====================================================
  - name: 'python:3.11'
    id: 'run-eval-tests'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "🔹 [Stage 1] Installing Dependencies..."
        pip install --upgrade pip
        pip install -r requirements.txt
        # Use -m pytest to avoid "module not found" errors
        python3 -m pytest tests/evaluate.py

  # =====================================================
  # STAGE 2: CLOUD RUN (Build -> Push -> Deploy)
  # =====================================================
  - name: 'gcr.io/cloud-builders/docker'
    id: 'build-container'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/brady-logistics-agent', '.']
    waitFor: ['run-eval-tests']

  - name: 'gcr.io/cloud-builders/docker'
    id: 'push-container'
    args: ['push', 'gcr.io/$PROJECT_ID/brady-logistics-agent']
    waitFor: ['build-container']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'deploy-cloud-run'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'brady-logistics-agent'
      - '--image=gcr.io/$PROJECT_ID/brady-logistics-agent'
      - '--region=us-central1'
      - '--allow-unauthenticated'
      - '--set-env-vars=GCP_PROJECT_ID=$PROJECT_ID'
    waitFor: ['push-container']

  # =====================================================
  # STAGE 3: AGENT ENGINE DEPLOY (Clean & Verified)
  # =====================================================
  - name: 'python:3.11'
    id: 'deploy-agent-engine'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "🔹 [Stage 3] Installing ADK & Telemetry Hooks..."
        pip install google-adk
        # Ensure telemetry packages are present in the final bundle
        echo "opentelemetry-sdk" >> requirements.txt
        echo "opentelemetry-exporter-google-cloud" >> requirements.txt

        echo "🔹 [Stage 3] Deploying Agent to Vertex AI..."
        # Fixed the duplicate --display_name and corrected spacing
        adk deploy agent_engine brady_agent \
          --project $PROJECT_ID \
          --region us-central1 \
          --display_name "Brady Logistics Agent" \
          --env_file .env \
          --requirements_file requirements.txt \
          --trace_to_cloud
    waitFor: ['run-eval-tests']

options:
  logging: CLOUD_LOGGING_ONLY