steps:
  # =====================================================
  # STAGE 1: QUALITY GATE (Run the Tests)
  # =====================================================
  - name: 'python:3.11'
    id: 'run-eval-tests'
    entrypoint: 'bash'
    env:
      - 'GCP_PROJECT_ID=$PROJECT_ID'
    args:
      - '-c'
      - |
        echo "🔹 [Stage 1] Installing Dependencies..."
        pip install -r requirements.txt
        
        echo "🔹 [Stage 1] Running Evaluation Loop..."
        python3 tests/evaluate.py

  # =====================================================
  # STAGE 2: CLOUD RUN DEPLOY (Web App)
  # =====================================================
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'deploy-cloud-run'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'brady-logistics-agent'
      - '--source=.'
      - '--region=us-central1'
      - '--allow-unauthenticated'
      - '--set-env-vars=GCP_PROJECT_ID=$PROJECT_ID'
      - '--clear-base-image'
    waitFor: ['run-eval-tests']

  # =====================================================
  # STAGE 3: AGENT ENGINE DEPLOY (Simplified & Robust)
  # =====================================================
  - name: 'python:3.11' 
    id: 'deploy-agent-engine'
    entrypoint: 'bash'
    env:
      - 'GCP_PROJECT_ID=$PROJECT_ID'
    args:
      - '-c'
      - |
        echo "🔹 [Stage 3] Installing Dependencies..."
        pip install --upgrade "google-cloud-aiplatform[reasoningengine,langchain]" google-adk python-dotenv

        echo "🔹 [Stage 3] Creating Bucket..."
        # Hardcoded bucket and region: simple and reliable.
        gcloud storage buckets create gs://adk_agent_engine_staging --location=us-central1 --uniform-bucket-level-access || true

        echo "🔹 [Stage 3] Patching Agent Code..."
        # We create a header file with the initialization code.
        # This injects the Project ID and Telemetry flags directly into the agent.
        cat <<EOF > header.py
        import os
        import vertexai
        
        # 1. Initialize Vertex AI immediately (Prevents Import Crash)
        vertexai.init(project='$PROJECT_ID', location='us-central1')
        
        # 2. Set Environment Variables (Enables Telemetry)
        os.environ['GCP_PROJECT_ID'] = '$PROJECT_ID'
        os.environ['GOOGLE_CLOUD_AGENT_ENGINE_ENABLE_TELEMETRY'] = 'true'
        os.environ['OTEL_INSTRUMENTATION_GENAI_CAPTURE_MESSAGE_CONTENT'] = 'true'
        EOF

        # Merge header + original file -> overwrite original agent.py
        cat header.py brady_agent/agent.py > brady_agent/agent_temp.py
        mv brady_agent/agent_temp.py brady_agent/agent.py

        echo "🔹 [Stage 3] Deploying..."
        cat <<EOF > run_deploy.py
        import vertexai
        from vertexai.preview import reasoning_engines
        from brady_agent.agent import root_agent 

        # Re-init for the deploy script itself so it can upload the code
        vertexai.init(project='$PROJECT_ID', location='us-central1', staging_bucket='gs://adk_agent_engine_staging')

        print("🚀 Deploying to Vertex AI...")
        remote_agent = reasoning_engines.ReasoningEngine.create(
            root_agent,
            requirements=[
                "google-cloud-aiplatform[reasoningengine,langchain]", 
                "python-dotenv", 
                "google-adk",
                "opentelemetry-sdk",
                "opentelemetry-exporter-google-cloud"
            ],
            display_name="Brady Logistics Agent",
            description="Logistics assistant (Observability Enabled)"
        )
        print(f"✅ Deployment Complete! Resource: {remote_agent.resource_name}")
        EOF

        python3 run_deploy.py

    waitFor: ['run-eval-tests']

timeout: '900s'