steps:
  # =====================================================
  # STAGE 1: QUALITY GATE (Run the Tests)
  # =====================================================
  - name: 'python:3.11'
    id: 'run-eval-tests'
    entrypoint: 'bash'
    env:
      - 'GCP_PROJECT_ID=$PROJECT_ID'
    args:
      - '-c'
      - |
        echo "🔹 [Stage 1] Installing Dependencies..."
        pip install -r requirements.txt
        
        echo "🔹 [Stage 1] Running Evaluation Loop..."
        python3 tests/evaluate.py

  # =====================================================
  # STAGE 2: CLOUD RUN DEPLOY (Web App)
  # =====================================================
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'deploy-cloud-run'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'brady-logistics-agent'
      - '--source=.'
      - '--region=us-central1'
      - '--allow-unauthenticated'
      - '--set-env-vars=GCP_PROJECT_ID=$PROJECT_ID'
      - '--clear-base-image'
    waitFor: ['run-eval-tests']

  # =====================================================
  # STAGE 3: AGENT ENGINE DEPLOY (Hardcoded Staging Bucket)
  # =====================================================
  - name: 'python:3.11' 
    id: 'deploy-agent-engine'
    entrypoint: 'bash'
    env:
      - 'GCP_PROJECT_ID=$PROJECT_ID'
      - 'REGION=us-central1' 
    args:
      - '-c'
      - |
        echo "🔹 [Stage 3] Installing LATEST Deploy Dependencies..."
        pip install --upgrade "google-cloud-aiplatform[reasoningengine,langchain]" google-adk python-dotenv

        # --- 1. CREATE BUCKET (HARDCODED) ---
        echo "🔹 [Stage 3] Ensuring bucket exists: gs://adk_agent_engine_staging"
        gcloud storage buckets create gs://adk_agent_engine_staging --location=$REGION --uniform-bucket-level-access || true

        echo "🔹 [Stage 3] Generating Deploy Script..."
        cat <<EOF > run_deploy.py
        import os
        import vertexai
        from vertexai.preview import reasoning_engines
        from brady_agent.agent import root_agent 

        project_id = os.environ.get("GCP_PROJECT_ID")
        location = os.environ.get("REGION", "us-central1")
        
        # --- 2. PYTHON CONFIG (HARDCODED) ---
        staging_bucket = "gs://adk_agent_engine_staging"

        print(f"🚀 Connecting to Vertex AI in {project_id}...")
        print(f"📂 Using Staging Bucket: {staging_bucket}")
        
        vertexai.init(
            project=project_id, 
            location=location, 
            staging_bucket=staging_bucket
        )

        print("🛠️  Wrapping agent in AdkApp for Telemetry...")
        if isinstance(root_agent, reasoning_engines.AdkApp):
            agent_to_deploy = root_agent
        else:
            agent_to_deploy = reasoning_engines.AdkApp(
                agent=root_agent, 
                enable_tracing=True
            )

        print("🚀 Deploying to Vertex AI...")
        remote_agent = reasoning_engines.ReasoningEngine.create(
            agent_to_deploy,
            requirements=[
                "google-cloud-aiplatform[reasoningengine,langchain]", 
                "python-dotenv", 
                "google-adk"
            ],
            display_name="Brady Logistics Agent",
            description="Logistics assistant (Observability Enabled)"
        )
        print(f"✅ Deployment Complete! Resource: {remote_agent.resource_name}")
        EOF

        echo "🔹 [Stage 3] Executing Deployment..."
        python3 run_deploy.py

    waitFor: ['run-eval-tests']

timeout: '900s'