steps:
  # =====================================================
  # STAGE 1: EVALUATION TESTS
  # =====================================================
  - name: 'python:3.11'
    id: 'run-eval-tests'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "🔹 Running Pytest..."
        pip install -r requirements.txt
        python3 -m pytest tests/

  # =====================================================
  # STAGE 2: BUILD WEB APP CONTAINER
  # =====================================================
  - name: 'gcr.io/cloud-builders/docker'
    id: 'build-container'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/brady-web-app', '.']
    waitFor: ['run-eval-tests']

  # =====================================================
  # STAGE 3: AGENT ENGINE DEPLOY (Elegant & Isolated)
  # =====================================================
  - name: 'python:3.11'
    id: 'deploy-agent-engine'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "🔹 Installing ADK..."
        pip install google-adk
        
        echo "🔹 Deploying Agent Engine to $PROJECT_ID..."
        
        # We explicitly use the .env from the repo.
        # It never sees your private .env.local because that's not in Git.
        # ADK version 1.23+ handles the project ID automatically from the environment.
        adk deploy agent_engine brady_agent \
          --project $PROJECT_ID \
          --region us-central1 \
          --display_name "Brady Logistics Agent" \
          --env_file .env \
          --requirements_file requirements.txt \
          --trace_to_cloud

    waitFor: ['run-eval-tests']

# No substitutions needed for the project ID as it's built-in.
# You can add other custom variables here if needed later.
options:
  logging: CLOUD_LOGGING_ONLY