steps:
  # =====================================================
  # STAGE 1: QUALITY GATE
  # =====================================================
  - name: 'python:3.11'
    id: 'run-eval-tests'
    entrypoint: 'bash'
    env:
      - 'GCP_PROJECT_ID=$PROJECT_ID'
    args:
      - '-c'
      - |
        echo "🔹 [Stage 1] Installing Dependencies..."
        pip install -r requirements.txt
        python3 tests/evaluate.py

  # =====================================================
  # STAGE 2: CLOUD RUN (Build -> Push -> Deploy)
  # =====================================================
  
  # 2a. Build the Docker Image explicitly
  - name: 'gcr.io/cloud-builders/docker'
    id: 'build-container'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/brady-logistics-agent', '.']
    waitFor: ['run-eval-tests']

  # 2b. Push the Image to Google Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    id: 'push-container'
    args: ['push', 'gcr.io/$PROJECT_ID/brady-logistics-agent']
    waitFor: ['build-container']

  # 2c. Deploy the Pre-Built Image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'deploy-cloud-run'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'brady-logistics-agent'
      - '--image=gcr.io/$PROJECT_ID/brady-logistics-agent'  # <--- Use the image we just built
      - '--region=us-central1'
      - '--allow-unauthenticated'
      - '--set-env-vars=GCP_PROJECT_ID=$PROJECT_ID'
    waitFor: ['push-container']

  # =====================================================
  # STAGE 3: AGENT ENGINE DEPLOY (The Proven Method)
  # =====================================================
  - name: 'python:3.11' 
    id: 'deploy-agent-engine'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        pip install google-adk
        # Use the shared file + inject the ID via the command line directly
        adk deploy agent_engine brady_agent \
          --project $PROJECT_ID \
          --region us-central1 \
          --display_name "Brady Logistics Agent" \
          --env_file .env.shared \
          --set-env-vars GCP_PROJECT_ID=$PROJECT_ID \
          --trace_to_cloud

    waitFor: ['run-eval-tests']

timeout: '1200s'